image:
  tag: dev
  repository: 932258881501.dkr.ecr.us-east-2.amazonaws.com/helloapp
  imagePullPolicy: Always

labels:
  env: "staging"
  cluster: "demo-cluster"

service:
  port: 80
  targetPort: 8080
  type: LoadBalancer
